### PR TITLE
Fixed the failing test

### PR DESCRIPTION
**Pull request by ascripcaru**
I hope now you can push the code to npmjs

### CODE REVIEW

**Comment by ascripcaru** [comment]
@levexis please take a look

**Comment by levexis** [comment]
Sorry, I hadn't noticed this but have now! Will update npmjs.

**Comment by levexis** [comment]
this is still failing in CI (linux ) and on OSX. 

 grunt-selenium-webdriver@0.2.471 test /home/ubuntu/grunt-selenium-webdriver
> grunt test

Running "clean:tests" (clean) task

Running "selenium_start" task
seleniumrc webdriver ready on 127.0.0.1:4445

Running "selenium_stop" task

Running "selenium_phantom_hub" task
registered phantomjs with hub running on 127.0.0.1:4445

Running "connect:e2e" (connect) task
Started connect web server on http://0.0.0.0:9000

Running "mochacli:e2e" (mochacli) task

/home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/_base.js:104
        vm.runInContext(opt_srcText, closure, src);
           ^
SyntaxError: Unexpected token )
    at goog.loadModuleFromSource_ (/home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
    at Object.goog.loadModule (/home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)
    at /home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6
    at Object.Context.closure.goog.retrieveAndExecModule_ (/home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/_base.js:135:8)
    at <anonymous>:1:6
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/_base.js:104:12)
    at Object.goog.importScript_ (/home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/lib/goog/base.js:879:9)
    at Object.goog.importModule_ (/home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/lib/goog/base.js:900:14)
    at Object.goog.writeScripts_ (/home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/lib/goog/base.js:1323:16)
    at Object.goog.require (/home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/lib/goog/base.js:663:14)
Warning:  Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.

npm test returned exit code 1

**Comment by levexis** [comment]
locally (OSX ) it is just hanging on selenium_phantom_hub_start

**Comment by ascripcaru** [comment]
On my fedora it works fine. all the tests are passing and all is green

**Comment by levexis** [comment]
thanks - It's failing on circleci too, tests are just hanging. They are running some flavour of linux I think, if you fancy taking a look I can add you to the project? Otherwise I probably won't get to this until xmas!

npm test

> grunt-selenium-webdriver@0.2.471 test /home/ubuntu/grunt-selenium-webdriver
> grunt test

Running "clean:tests" (clean) task

Running "selenium_start" task
seleniumrc webdriver ready on 127.0.0.1:4445

Running "selenium_stop" task

Running "selenium_phantom_hub" task
registered phantomjs with hub running on 127.0.0.1:4445

Running "connect:e2e" (connect) task
Started connect web server on http://0.0.0.0:9000

Running "mochacli:e2e" (mochacli) task

/home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/_base.js:104
        vm.runInContext(opt_srcText, closure, src);
           ^
SyntaxError: Unexpected token )
    at goog.loadModuleFromSource_ (/home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/lib/goog/base.js:1123:19)
    at Object.goog.loadModule (/home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/lib/goog/base.js:1085:46)
    at /home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/lib/webdriver/promise.js:1:6
    at Object.Context.closure.goog.retrieveAndExecModule_ (/home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/_base.js:135:8)
    at <anonymous>:1:6
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (/home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/_base.js:104:12)
    at Object.goog.importScript_ (/home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/lib/goog/base.js:879:9)
    at Object.goog.importModule_ (/home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/lib/goog/base.js:900:14)
    at Object.goog.writeScripts_ (/home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/lib/goog/base.js:1323:16)
    at Object.goog.require (/home/ubuntu/grunt-selenium-webdriver/node_modules/selenium-webdriver/lib/goog/base.js:663:14)
Warning:  Use --force to continue.

**Comment by ascripcaru** [comment]
I will try to take a look this week

**Comment by ascripcaru** [comment]
@levexis I did 3 pushes and I fixed the problem.also I updated the jar. selenium-webdriver has a known bug and that was the reason for the failing tests. the solution for that was to use `"selenium-webdriver": "2.47.0"` this version which doesn't have that bug.

**Comment by levexis** [comment]
brilliant, that was a very nice surprise when I logged into to circleci and saw green tests for this! I have published the npm.

**Pull request merged**
