### PR TITLE
Upgrading to selenium 2.45.0

### LINKED ISSUE #18: Selenium Jar 2.45 for Firefox 36
Firefox 36 requires a new selenium jar in order to work.

### PR DESCRIPTION
**Pull request by justinjmoses**
Fixes #18

### CODE REVIEW

**Comment by nwhite89** [comment]
:+1: it would be great to get this in and released this is currently causing me a vast amount of problems although it would be nice in the future to be able to pass in the JAR version from Grunt to make these problems quicker and easier to fix ?

**Comment by levexis** [comment]
Agreed, if you submit a pull request with that added then I'll merge it 
in. Will take a look over the weekend. Thanks.

**Comment by nwhite89** [comment]
I will try and get this added feature in as well however, don't let that block @justinjmoses PR

**Comment by justinjmoses** [comment]
@levexis Are you open to not having the binaries in source control but rather downloading on the start of the task if the given JAR isn't available locally?

**Comment by levexis** [comment]
mmm, my concern is compatibility with phantom + OS + whatever the tests 
are written in. I could see my build breaking by not updating anything 
so it would need to have a default. For example when I merged the PR my 
e2e tests have failed on circle CI so I need to check what's happened!

I really like the idea of being able to specify a specific version and 
it gets it for you, with an option for "latest". My gut says we should 
bundle a version as you may not have internet when you go to run your tests.

**Comment by nwhite89** [comment]
It would be perhaps nice to have it as an option, the latest known compatible version is bundled with the repo (like it is done now) however, you have the option to change this passing the version you want within the Grunt options then that way it is on the the person doing the change to deal with compatibility options. It provides an easier way of different versions?

**Comment by justinjmoses** [comment]
makes sense.

**Pull request merged**
