### PR TITLE
Upgrade phantomjs

### PR DESCRIPTION
**Pull request by mikesherov**
A new PhantomJS was released on Monday. Please let me know if I need to do anything else to get this PR merged. Thanks!

### CODE REVIEW

**Comment by mikesherov** [comment]
ping

**Comment by darkwebdev** [comment]
:+1:

**Comment by mikesherov** [comment]
Thanks for merging! Are you planning on publishing to npm today?

**Comment by ascripcaru** [comment]
I don't have rights. @levexis needs to do that.

**Comment by levexis** [comment]
Sorry, hadn't noticed this was outstanding - will publish npm now.

**Comment by levexis** [comment]
This failed on CI and for me locally due to this bug - https://github.com/detro/ghostdriver/issues/394. The fix has still not got into latest packages. I did seem to have it working with an edited phantomjs binary but is not working now and would require versions for other platforms ( i am OSX ). I don't have any more time I can spend on this, seems this is a well known issue.

**Pull request merged**
